apiVersion: v1
kind: Namespace
metadata:
  name: kafka-infra
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kafka-infra-operator-group
  namespace: kafka-infra
spec:
  targetNamespaces:
    - kafka-infra
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
  namespace: kafka-infra
spec:
  channel: stable
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
