apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: app-user
  namespace: kafka-infra
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: mensagens-topic
          patternType: literal
        operations: [Read, Write, Create, Describe]
      - resource:
          type: group
          name: meu-grupo-consumidor
          patternType: literal
        operations: [Read, Describe]
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: mensagens-topic
  namespace: kafka-infra
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
