apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-app-config
  namespace: kafka-app
data:
  KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.kafka-infra.svc.cluster.local:9092"
  KAFKA_CONSUMER_GROUP: "meu-grupo-consumidor"
  KAFKA_SECURITY_PROTOCOL: "PLAINTEXT"
  KAFKA_TOPIC: "mensagens-topic"