apiVersion: v1
kind: Secret
metadata:
  name: kafka-app-secret
  namespace: kafka-app
type: Opaque
stringData:
  KAFKA_SASL_JAAS_CONFIG: |
    org.apache.kafka.common.security.scram.ScramLoginModule required username="meu-usuario" password="minha-senha";